---
title: "Canadian Wages"
---

## Setup R Packages

```{r}
library(tidyverse)
library(mosaic) # Our all-in-one package
library(skimr) # Looking at data
library(janitor) # Clean the data
library(naniar) # Handle missing data
library(visdat) # Visualise missing data
library(tinytable) # Printing Static Tables for our data
library(DT) # Interactive Tables for our data
library(crosstable) # Multiple variable summaries
library(ggformula) # Graphing
```

## Read Data

```{r}
can_wages <- read_csv("Data/Canadian_Wages.csv")
```

## Viewing the Data

```{r}
dplyr::glimpse(can_wages)
```

## Data Cleaning

```{r}
wages_modified <- can_wages %>%
  janitor::clean_names(case = "snake") # clean names

wages_modified
```

## Replacing NA

```{r}
wages_modified1 <- wages_modified %>%
  naniar::replace_with_na_all(condition = ~ .x %in% common_na_numbers) %>%
  replace_with_na_all(condition = ~ .x %in% common_na_strings)
glimpse(wages_modified1)
```

## Dropping NA

```{r}
wages_modified_clean <- wages_modified1 %>% 
 tidyr::drop_na() 
wages_modified_clean
```

## Missing Data

```{r}
visdat::vis_miss(wages_modified_clean)
visdat::vis_dat(wages_modified_clean, sort_type = TRUE, palette = "cb_safe")
```

## Data Munging

```{r}
wages_munged <- wages_modified_clean %>%
  mutate(
    sex = as.factor(sex),
    language = as.factor(language)
  ) %>%
  # arrange the Qualitative (factors) first, then Quantitative
  dplyr::relocate(where(is.factor), .after = rownames)

glimpse(wages_munged)

```

## Table Captioning (Title)

```{r}
wages_munged %>%
  head(10) %>%
  tinytable::tt(caption = "Wage Dataset (Clean)") %>%
  tinytable::theme_html(class = "table table-hover table-striped table-condensed") %>%
  style_tt(fontsize = 0.8) %>%
  stats::setNames(c("Row ID", "Sex", "Language", "Wages", "Education", "Age"))

```

## Quant Bar Graph

```{r}
# Histogram of Wages
gf_histogram(~wages, data = wages_munged, bins = 30, fill = "pink") %>%
  gf_labs(title = "Distribution of Wages", x = "Wages", y = "Count")

# Histogram of Education
gf_histogram(~education, data = wages_munged, bins = 20, fill = "purple") %>%
  gf_labs(title = "Distribution of Education Years", x = "Years of Education", y = "Count")

# Histogram of Age
gf_histogram(~age, data = wages_munged, bins = 20, fill = "blue") %>%
  gf_labs(title = "Distribution of Age", x = "Age", y = "Count")

```

## Quant Bar Graph

```{r}
# Bar graph of Sex
gf_bar(~sex, data = wages_munged, fill = ~sex) %>%
  gf_labs(title = "Counts of Respondents by Sex", x = "Sex", y = "Count")

# Bar graph of Language
gf_bar(~language, data = wages_munged, fill = ~language) %>%
  gf_labs(title = "Counts of Respondents by Language", x = "Language", y = "Count")

```

## Quant Log Scale

```{r}
# Wages by Sex
gf_boxplot(sex ~ wages, data = wages_munged, fill = ~sex, orientation = "y") %>%
  gf_labs(title = "Wages by Sex", x = "Wages", y = "Sex")

# Wages by Language
gf_boxplot(language ~ wages, data = wages_munged, fill = ~language, orientation = "y") %>%
  gf_labs(title = "Wages by Language", x = "Wages", y = "Language")

# Education by Sex
gf_boxplot(sex ~ education, data = wages_munged, fill = ~sex, orientation = "y") %>%
  gf_labs(title = "Education Years by Sex", x = "Education (Years)", y = "Sex")

```

```{r}
dplyr::count(wages_munged)
dplyr::summarise(wages_munged)
crosstable::crosstable(wages_munged)
```
