---
title: "Classwork 2"
---

## Intro

I am going to do weird things in R

## Setup R packages

```{r}
#/ label: setup
library(tidyverse)
library(mosaic) # Our all-in-one package
library(skimr) # Looking at data
library(visdat) # Mapping missing data
library(naniar) # Missing data visualization and munging
library(janitor) # Clean the data
library(tinytable) # Printing Tables for our data

```

## Read the Data

```{r}
fastfood <- read_csv("https://vincentarelbundock.github.io/Rdatasets/csv/openintro/fastfood.csv") %>% 
 janitor::clean_names(case = "snake") # clean names
```

## Expanding Data more

```{r}
base::names(fastfood) 
dplyr::glimpse(fastfood)
dim(fastfood)
utils::str(fastfood)
visdat::vis_dat(fastfood)
visdat::vis_miss(fastfood)
```

## Removing Missing Data

```{r}
fastfood_modified <- fastfood %>% tidyr::drop_na()
fastfood_modified
```

## Another way

```{r}
fastfood_modified2 <- fastfood %>% drop_na(calcium)
fastfood_modified2
```

## Remove Columns entirely

```{r}
fastfood_modified3 <- fastfood %>% 
  select(-c(vit_a, vit_c))
fastfood_modified3
```

## Converting it into a factor

```{r}
fastfood_modified <- fastfood_modified %>%
  mutate(
    restaurant = as.factor(restaurant),
    salad = as.factor(salad),
    item = as.factor(item)
  ) %>%
  rename("dish" = item) %>% # rename item to dish

  # arrange the Qual variables first, Quant next
  dplyr::relocate(where(is.factor), .after = rownames)
  
glimpse(fastfood_modified)
```

## Clean Data representing

```{r}
tt(fastfood_modified3)
```
