---
title: "Classwork 9"
author: Meenakshi
date: 21/10/25
categories: Classwork
description: Learning inference for a single mean and for two independant means
format: html
---

## SetUp R Packages

```{r}
library(tidyverse)
library(tinytable)
library(mosaic)
library(ggformula)
library(infer)
library(broom) # Clean test results in tibble form
library(resampledata3) # Datasets from Chihara and Hesterberg's book
library(openintro) # More datasets
library(visStatistics) # One package to rule them all
library(ggstatsplot)
```

## Case Study 1: Toy Data

```{r}
set.seed(42) # for replication
#
# Data as individual vectors
# ( for t.tests etc)
# Generate normally distributed data with mean = 2, sd = 2, length = 50
y <- rnorm(n = 50, mean = 2, sd = 2)

# And as tibble too
mydata <- tibble(y = y)
mydata
```

### Inspecting and Charting Data

```{r}
## Set Plot theme
ggplot2::theme_set(new = theme_classic())

mydata %>%
  gf_density(~y) %>%
  gf_fitdistr(dist = "dnorm") %>%
  gf_labs(
    title = "Densities of Original Data Variables",
    subtitle = "Compared with Normal Density"
  )
```

### Inference

```{r}
# t-test
t1 <- mosaic::t_test(
  y, # Name of variable
  mu = 0, # belief of population mean
  alternative = "two.sided"
) %>% # Check both sides

  broom::tidy() # Make results presentable, and plottable!!
t1
```

## Case Study 2: Exam Data

```{r}
data("exam_grades", package = "openintro")
exam_grades
```

### Inspecting and Charting Data

```{r}
ggplot2::theme_set(new = theme_classic())

exam_grades %>%
  gf_density(~course_grade) %>%
  gf_fitdistr(dist = "dnorm") %>%
  gf_labs(
    title = "Density of Course Grade",
    subtitle = "Compared with Normal Density"
  )
```

### Inference

```{r}
# t-test
t4 <- mosaic::t_test(
  exam_grades$course_grade, # Name of variable
  mu = 80, # belief
  alternative = "two.sided"
) %>% # Check both sides
  broom::tidy()
t4
```

## Case Study 3: Math Anxiety

```{r}
data("MathAnxiety", package = "resampledata")
MathAnxiety
```

### Inspecting and Charting Data

```{r}

glimpse(MathAnxiety)
skimr::skim(MathAnxiety) %>%
  tt() %>%
  theme_striped(font) %>%
  style_tt(fontsize = 0.75)
```

### Inference

```{r}
t1_amas <- mosaic::t_test(AMAS ~ Gender, data = MathAnxiety)

t1_amas %>%
  broom::tidy()
```

## Case Study 4: Youth Risk Behavior Surveillance System (YRBSS) survey

```{r}
data(yrbss, package = "openintro")
yrbss
```

### Inspecting and Charting Data

```{r}
yrbss_inspect <- inspect(yrbss)
yrbss_inspect$categorical
yrbss_inspect$quantitative
```

### Inference

```{r}
wilcox.test(weight ~ gender,
  data = yrbss_select_gender,
  conf.int = TRUE,
  conf.level = 0.95
) %>%
  broom::tidy()
```
